services:
  web:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0
    depends_on:
      - postgres
      - redis
      - solr
  solr:
    image: solr
    user: "8983:8983"
    ports:
     - "8983:8983"
    volumes:
      - ./blacklight-core:/var/solr/data/blacklight-core:rw
    command: solr-precreate blacklight-core
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: seattle_library_development
    volumes:
      - postgres-data:/var/lib/postgresql/data
  sidekiq:
    build:
      context: .
      dockerfile: development.Dockerfile
    depends_on:
      - redis
      - postgres
volumes:
  redis-data:
  postgres-data:
