load_defaults: 8.3.0

default: &default
  adapter: solr
  url: <%= ENV['LOCAL_SOLR'] %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default
  url: <%= ENV['FULL_SOLR'] %>
